# Generated by Django 5.2.3 on 2025-06-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('year_of_study', models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Final Year', 'Final Year')], max_length=20)),
                ('preferred_contact_method', models.CharField(choices=[('Phone', 'Phone'), ('Email', 'Email'), ('SMS', 'SMS')], max_length=10)),
                ('fitness_goals', models.JSONField(blank=True, null=True)),
                ('roll_no', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('fitness_challenges', models.TextField(blank=True, null=True)),
                ('gym_member_before', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('terms_agreed', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('year_of_study', models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Final Year', 'Final Year')], max_length=20)),
                ('preferred_contact_method', models.CharField(choices=[('Phone', 'Phone'), ('Email', 'Email'), ('SMS', 'SMS')], max_length=10)),
                ('fitness_goals', models.JSONField(blank=True, null=True)),
                ('roll_no', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('fitness_challenges', models.TextField(blank=True, null=True)),
                ('gym_member_before', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('terms_agreed', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YogaRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('registration_number', models.CharField(max_length=50)),
                ('branch', models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Final Year', 'Final Year'), ('Faculty', 'Faculty')], max_length=20)),
                ('health_condition', models.CharField(choices=[('High Blood Pressure', 'High Blood Pressure'), ('Low Blood Pressure', 'Low Blood Pressure'), ('Asthma', 'Asthma'), ('Surgery in the last 3 years', 'Surgery in the last 3 years'), ('Fainting Spells/Dizzy', 'Fainting Spells/Dizzy'), ('Other', 'Other')], max_length=50)),
                ('other_health_issues', models.TextField(blank=True, null=True)),
                ('acknowledgement', models.BooleanField(default=False)),
                ('submission_date', models.DateField()),
                ('terms_agreed', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
